 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobType = IDL.Variant({
  'internship' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const Opportunity = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'jobType' : JobType,
  'skill' : IDL.Text,
  'company' : IDL.Text,
  'applicationLink' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'askAIRaw' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'generateContestRaw' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generatePracticeRaw' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'generatePrepPlanRaw' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobType = IDL.Variant({
    'internship' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const Opportunity = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'jobType' : JobType,
    'skill' : IDL.Text,
    'company' : IDL.Text,
    'applicationLink' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'askAIRaw' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'generateContestRaw' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generatePracticeRaw' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'generatePrepPlanRaw' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };